version: '3'
services:
    devwks1000:
        image: alok806/devwks1000
        volumes:
            - /Users/alwadhwa/Desktop/aci/output:/root/output
            - /Users/alwadhwa/Desktop/aci/input:/root/input
